#!/bin/bash

if [ $# -ne 1 ]; then
  echo "usage: ./go <sub-dif>/<python file>" >&2
  exit 192
fi
ry_dir=$(echo "$1" | cut -d'/' -f1)
ry_py=$(echo "$1"  | cut -d'/' -f2)
cd "$ry_dir" || exit 192
FLASK_APP="$ry_py" flask run
cd - || exit 192
